//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_videoteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class AktivnostKorisnika
    {
        public int ID_Korisnik { get; set; }
        public int ID_Film { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
