//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_videoteka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PI2247_DBEntities1 : DbContext
    {
        public PI2247_DBEntities1()
            : base("name=PI2247_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AktivnostKorisnika> AktivnostKorisnikas { get; set; }
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
    }
}
